#!/usr/bin/env bash
# Post-checkout hook: create a Lakebase database branch for the current Git branch.
# Install: ./scripts/install-hook.sh
# Only runs on branch checkout (third argument is 1). See: https://git-scm.com/docs/githooks#_post_checkout

set -e
PREV_HEAD="$1"
NEW_HEAD="$2"
BRANCH_CHECKOUT="$3"

if [ "$BRANCH_CHECKOUT" != "1" ]; then
  exit 0
fi

WORK_TREE="$(git rev-parse --show-toplevel)"
cd "$WORK_TREE"

# Detached HEAD: skip
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
if [ -z "$BRANCH" ] || [ "$BRANCH" = "HEAD" ]; then
  exit 0
fi

# Load .env if present
if [ -f .env ]; then
  set -a
  # shellcheck source=/dev/null
  source .env 2>/dev/null || true
  set +a
fi

# Bootstrap .env from .env.example if missing
if [ ! -f .env ] && [ -f .env.example ]; then
  cp .env.example .env
  echo "Lakebase: created .env from .env.example. Set LAKEBASE_PROJECT_ID and run checkout again."
  exit 0
fi

# --- Prerequisites ---
PROJ_ID="${LAKEBASE_PROJECT_ID:-}"
if [ -z "$PROJ_ID" ]; then
  echo "Lakebase: set LAKEBASE_PROJECT_ID in .env"
  exit 0
fi

if ! command -v databricks >/dev/null 2>&1; then
  echo "Lakebase: databricks CLI not found. Install and run 'databricks auth login'."
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "Lakebase: jq is required. Install: brew install jq"
  exit 1
fi

PROJ_PATH="projects/${PROJ_ID}"
DB_NAME="databricks_postgres"

# --- Helper: update .env and application-local.properties with connection info ---
# Maven/Spring do not load .env; they use application-local.properties (spring.config.import).
# So we must write the branch URL to both, or Maven will use whatever is in application-local.properties
# (e.g. production from a previous run) and schema would go to the wrong branch.
update_env() {
  local host="$1" user="$2" pass="$3" branch_id="$4"
  # URL-encode the username (@ -> %40, etc.)
  local encoded_user
  encoded_user="$(python3 -c "import urllib.parse; print(urllib.parse.quote('$user', safe=''))" 2>/dev/null || echo "$user")"
  local database_url="postgresql://${encoded_user}:${pass}@${host}:5432/${DB_NAME}?sslmode=require"

  if [ -f .env ]; then
    grep -v "^DATABASE_URL=" .env \
      | grep -v "^DB_USERNAME=" \
      | grep -v "^DB_PASSWORD=" \
      | grep -v "^SPRING_DATASOURCE_URL=" \
      | grep -v "^SPRING_DATASOURCE_USERNAME=" \
      | grep -v "^SPRING_DATASOURCE_PASSWORD=" \
      | grep -v "^LAKEBASE_BRANCH_ID=" \
      | grep -v "^LAKEBASE_HOST=" \
      > .env.tmp 2>/dev/null || true
  else
    touch .env.tmp
  fi

  {
    echo "LAKEBASE_HOST=${host}"
    echo "LAKEBASE_BRANCH_ID=${branch_id}"
    echo "DATABASE_URL=${database_url}"
    echo "DB_USERNAME=${user}"
    echo "DB_PASSWORD=${pass}"
  } >> .env.tmp

  mv .env.tmp .env

  # Write application-local.properties only for Java/Spring projects (pom.xml present)
  if [ -f pom.xml ]; then
    local jdbc_url="jdbc:postgresql://${host}:5432/${DB_NAME}?sslmode=require"
    {
      echo "# Auto-generated by post-checkout hook for branch: ${branch_id}"
      echo "spring.datasource.url=${jdbc_url}"
      echo "spring.datasource.username=${user}"
      echo "spring.datasource.password=${pass}"
    } > application-local.properties
  fi
}

# --- Helper: get credential and email ---
get_credential() {
  local endpoint_path="$1"
  TOKEN="$(databricks postgres generate-database-credential "$endpoint_path" -o json 2>/dev/null \
    | jq -r '.token // empty')"
  EMAIL="$(databricks current-user me -o json 2>/dev/null \
    | jq -r '.userName // .emails[0].value // empty')"
}

# --- Helper: get endpoint host, creating if needed ---
get_or_create_endpoint() {
  local branch_path="$1"
  local ep_host

  ep_host="$(databricks postgres list-endpoints "$branch_path" -o json 2>/dev/null \
    | jq -r '.[0].status.hosts.host // empty')"

  if [ -z "$ep_host" ]; then
    echo "Lakebase: creating endpoint..." >&2
    databricks postgres create-endpoint "$branch_path" "primary" \
      --json '{"spec": {"endpoint_type": "ENDPOINT_TYPE_READ_WRITE", "autoscaling_limit_min_cu": 2, "autoscaling_limit_max_cu": 4}}' >/dev/null 2>&1 || true

    echo "Lakebase: waiting for endpoint to be active..." >&2
    for _ in $(seq 1 24); do
      local state
      state="$(databricks postgres list-endpoints "$branch_path" -o json 2>/dev/null \
        | jq -r '.[0].status.current_state // empty')"
      [ "$state" = "ACTIVE" ] && break
      sleep 5
    done

    ep_host="$(databricks postgres list-endpoints "$branch_path" -o json 2>/dev/null \
      | jq -r '.[0].status.hosts.host // empty')"
  fi

  echo "$ep_host"
}

# --- Find the default (main) Lakebase branch ---
# API returns { "branches": [ ... ] }; CLI may unwrap to [ ... ]. Support both.
DEFAULT_BRANCH_UID="$(databricks postgres list-branches "$PROJ_PATH" -o json 2>/dev/null \
  | jq -r '(if type == "array" then . elif type == "object" then (.branches // .items // []) else [] end) | .[] | select((.status.default == true) or (.is_default == true)) | (.uid // .id // (if .name then (.name | split("/") | last) else empty end))' | head -1)"

if [ -z "$DEFAULT_BRANCH_UID" ]; then
  echo "Lakebase: could not find default branch. Check LAKEBASE_PROJECT_ID and CLI auth."
  exit 1
fi

# --- main/master: point to the default Lakebase branch ---
if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
  echo "Lakebase: on $BRANCH, connecting to default Lakebase branch ($DEFAULT_BRANCH_UID)..."
  BRANCH_PATH="${PROJ_PATH}/branches/${DEFAULT_BRANCH_UID}"

  HOST="$(get_or_create_endpoint "$BRANCH_PATH")"
  if [ -z "$HOST" ]; then
    echo "Lakebase: could not get endpoint host for default branch."
    exit 0
  fi

  get_credential "${BRANCH_PATH}/endpoints/primary"
  if [ -z "$TOKEN" ] || [ -z "$EMAIL" ]; then
    echo "Lakebase: could not get credential. Set DATABASE_URL in .env manually."
    exit 0
  fi

  update_env "$HOST" "$EMAIL" "$TOKEN" "$DEFAULT_BRANCH_UID"
  echo "Lakebase: $BRANCH -> default branch ($DEFAULT_BRANCH_UID). Updated .env."
  exit 0
fi

# --- Feature branch: create Lakebase branch from default ---
# Sanitize git branch name for Lakebase branch ID
LAKEBASE_BRANCH="$(echo "$BRANCH" | sed 's/\//-/g' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | cut -c1-63)"
BRANCH_PATH="${PROJ_PATH}/branches/${LAKEBASE_BRANCH}"
SOURCE_BRANCH="${PROJ_PATH}/branches/${DEFAULT_BRANCH_UID}"

# Check if branch already exists
BRANCH_EXISTS="$(databricks postgres list-branches "$PROJ_PATH" -o json 2>/dev/null \
  | jq -r --arg uid "$LAKEBASE_BRANCH" '(if type == "array" then . elif type == "object" then (.branches // .items // []) else [] end) | .[] | select((.name | type == "string" and (endswith("/branches/" + $uid) or (split("/") | last == $uid))) or (.uid == $uid) or (.id == $uid)) | (.name // .uid // .id)' | head -1)"

if [ -z "$BRANCH_EXISTS" ]; then
  echo "Lakebase: creating branch '$LAKEBASE_BRANCH' from default ($DEFAULT_BRANCH_UID)..."
  databricks postgres create-branch "$PROJ_PATH" "$LAKEBASE_BRANCH" \
    --json "{\"spec\": {\"source_branch\": \"$SOURCE_BRANCH\", \"no_expiry\": true}}" >/dev/null 2>&1 || true
else
  echo "Lakebase: branch '$LAKEBASE_BRANCH' already exists."
fi

# Wait for branch READY (up to 2 min)
echo "Lakebase: waiting for branch to be ready..."
STATE=""
for _ in $(seq 1 24); do
  STATE="$(databricks postgres list-branches "$PROJ_PATH" -o json 2>/dev/null \
    | jq -r --arg uid "$LAKEBASE_BRANCH" '(if type == "array" then . elif type == "object" then (.branches // .items // []) else [] end) | .[] | select((.name | type == "string" and (endswith("/branches/" + $uid) or (split("/") | last == $uid))) or (.uid == $uid) or (.id == $uid)) | .status.current_state // empty' | head -1)"
  [ "$STATE" = "READY" ] && break
  sleep 5
done

if [ "$STATE" != "READY" ]; then
  echo "Lakebase: branch '$LAKEBASE_BRANCH' not ready (state: ${STATE:-unknown}). Try again later."
  exit 0
fi

# Get or create endpoint
HOST="$(get_or_create_endpoint "$BRANCH_PATH")"
if [ -z "$HOST" ]; then
  echo "Lakebase: could not get endpoint host for '$LAKEBASE_BRANCH'. Set DATABASE_URL in .env manually."
  exit 0
fi

# Generate credential
get_credential "${BRANCH_PATH}/endpoints/primary"
if [ -z "$TOKEN" ] || [ -z "$EMAIL" ]; then
  echo "Lakebase: could not get credential. Set DATABASE_URL in .env manually (host: $HOST)."
  exit 0
fi

update_env "$HOST" "$EMAIL" "$TOKEN" "$LAKEBASE_BRANCH"
echo "Lakebase: branch '$LAKEBASE_BRANCH' ready. Updated .env with DATABASE_URL."
