#!/usr/bin/env bash
# Refresh Lakebase short-lived credential and optionally run a command (e.g. start the app).
# Use for long-running dev sessions after the post-checkout token has expired.
# Usage:
#   ./scripts/refresh-token.sh                    # refresh only
#   ./scripts/refresh-token.sh ./mvnw spring-boot:run
set -e

WORK_TREE="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$WORK_TREE" ]; then
  echo "refresh-token: must run from a git repo."
  exit 1
fi
cd "$WORK_TREE"

# Load .env
if [ ! -f .env ]; then
  echo "refresh-token: .env not found. Run from repo root after checkout (post-checkout creates .env)."
  exit 1
fi
set -a
# shellcheck source=/dev/null
source .env 2>/dev/null || true
set +a

PROJ_ID="${LAKEBASE_PROJECT_ID:-}"
if [ -z "$PROJ_ID" ]; then
  echo "refresh-token: set LAKEBASE_PROJECT_ID in .env"
  exit 1
fi

if ! command -v databricks >/dev/null 2>&1; then
  echo "refresh-token: databricks CLI not found."
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "refresh-token: jq is required. Install: brew install jq"
  exit 1
fi

PROJ_PATH="projects/${PROJ_ID}"
DB_NAME="databricks_postgres"

# Same as post-checkout: write connection info to .env and application-local.properties
update_env() {
  local host="$1" user="$2" pass="$3" branch_id="$4"
  local jdbc_url="jdbc:postgresql://${host}:5432/${DB_NAME}?sslmode=require"

  grep -v "^SPRING_DATASOURCE_URL=" .env \
    | grep -v "^SPRING_DATASOURCE_USERNAME=" \
    | grep -v "^SPRING_DATASOURCE_PASSWORD=" \
    | grep -v "^LAKEBASE_BRANCH_ID=" \
    | grep -v "^LAKEBASE_HOST=" \
    > .env.tmp 2>/dev/null || true

  {
    echo "LAKEBASE_HOST=${host}"
    echo "LAKEBASE_BRANCH_ID=${branch_id}"
    echo "SPRING_DATASOURCE_URL=${jdbc_url}"
    echo "SPRING_DATASOURCE_USERNAME=${user}"
    echo "SPRING_DATASOURCE_PASSWORD=${pass}"
  } >> .env.tmp

  mv .env.tmp .env

  {
    echo "# Auto-generated by refresh-token.sh for branch: ${branch_id}"
    echo "spring.datasource.url=${jdbc_url}"
    echo "spring.datasource.username=${user}"
    echo "spring.datasource.password=${pass}"
  } > application-local.properties
}

get_credential() {
  local endpoint_path="$1"
  TOKEN="$(databricks postgres generate-database-credential "$endpoint_path" -o json 2>/dev/null \
    | jq -r '.token // empty')"
  EMAIL="$(databricks current-user me -o json 2>/dev/null \
    | jq -r '.userName // .emails[0].value // empty')"
}

BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
if [ -z "$BRANCH" ] || [ "$BRANCH" = "HEAD" ]; then
  echo "refresh-token: not on a branch (detached HEAD). Checkout a branch first."
  exit 1
fi

# Resolve Lakebase branch path (same logic as post-checkout)
DEFAULT_BRANCH_UID="$(databricks postgres list-branches "$PROJ_PATH" -o json 2>/dev/null \
  | jq -r '(if type == "array" then . elif type == "object" then (.branches // .items // []) else [] end) | .[] | select((.status.default == true) or (.is_default == true)) | (.uid // .id // (if .name then (.name | split("/") | last) else empty end))' | head -1)"

if [ -z "$DEFAULT_BRANCH_UID" ]; then
  echo "refresh-token: could not find default Lakebase branch. Check LAKEBASE_PROJECT_ID and CLI auth."
  exit 1
fi

if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
  BRANCH_PATH="${PROJ_PATH}/branches/${DEFAULT_BRANCH_UID}"
  BRANCH_ID="$DEFAULT_BRANCH_UID"
else
  LAKEBASE_BRANCH="$(echo "$BRANCH" | sed 's/\//-/g' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | cut -c1-63)"
  BRANCH_PATH="${PROJ_PATH}/branches/${LAKEBASE_BRANCH}"
  BRANCH_ID="$LAKEBASE_BRANCH"
fi

# Get existing endpoint host (do not create)
HOST="$(databricks postgres list-endpoints "$BRANCH_PATH" -o json 2>/dev/null \
  | jq -r '.[0].status.hosts.host // empty')"

if [ -z "$HOST" ]; then
  echo "refresh-token: no endpoint for branch '$BRANCH_ID'. Run 'git checkout' to create branch and endpoint, then retry."
  exit 1
fi

get_credential "${BRANCH_PATH}/endpoints/primary"
if [ -z "$TOKEN" ] || [ -z "$EMAIL" ]; then
  echo "refresh-token: could not generate credential. Check 'databricks auth' and endpoint."
  exit 1
fi

update_env "$HOST" "$EMAIL" "$TOKEN" "$BRANCH_ID"
echo "Lakebase: token refreshed for branch '$BRANCH_ID'."

if [ $# -gt 0 ]; then
  exec "$@"
else
  echo "Run your app with: ./mvnw spring-boot:run  (or: ./scripts/refresh-token.sh ./mvnw spring-boot:run)"
fi
