#!/usr/bin/env bash
# Connect to the main (default) Lakebase branch and update .env and application-local.properties.
# Run from your terminal (Databricks CLI must be authenticated).
# Usage: ./scripts/connect-main-branch.sh
set -e

WORK_TREE="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$WORK_TREE" ]; then
  echo "connect-main-branch: must run from a git repo."
  exit 1
fi
cd "$WORK_TREE"

if [ ! -f .env ]; then
  echo "connect-main-branch: .env not found. Copy .env.example to .env and set LAKEBASE_PROJECT_ID and Databricks auth."
  exit 1
fi
set -a
# shellcheck source=/dev/null
source .env 2>/dev/null || true
set +a

PROJ_ID="${LAKEBASE_PROJECT_ID:-}"
if [ -z "$PROJ_ID" ]; then
  echo "connect-main-branch: set LAKEBASE_PROJECT_ID in .env"
  exit 1
fi

if ! command -v databricks >/dev/null 2>&1; then
  echo "connect-main-branch: databricks CLI not found."
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "connect-main-branch: jq is required. Install: brew install jq"
  exit 1
fi

PROJ_PATH="projects/${PROJ_ID}"
DB_NAME="databricks_postgres"

update_env() {
  local host="$1" user="$2" pass="$3" branch_id="$4"
  local jdbc_url="jdbc:postgresql://${host}:5432/${DB_NAME}?sslmode=require"

  grep -v "^SPRING_DATASOURCE_URL=" .env \
    | grep -v "^SPRING_DATASOURCE_USERNAME=" \
    | grep -v "^SPRING_DATASOURCE_PASSWORD=" \
    | grep -v "^LAKEBASE_BRANCH_ID=" \
    | grep -v "^LAKEBASE_HOST=" \
    > .env.tmp 2>/dev/null || true

  {
    echo "LAKEBASE_HOST=${host}"
    echo "LAKEBASE_BRANCH_ID=${branch_id}"
    echo "SPRING_DATASOURCE_URL=${jdbc_url}"
    echo "SPRING_DATASOURCE_USERNAME=${user}"
    echo "SPRING_DATASOURCE_PASSWORD=${pass}"
  } >> .env.tmp

  mv .env.tmp .env

  {
    echo "# Auto-generated by connect-main-branch.sh for branch: ${branch_id}"
    echo "spring.datasource.url=${jdbc_url}"
    echo "spring.datasource.username=${user}"
    echo "spring.datasource.password=${pass}"
  } > application-local.properties
}

get_credential() {
  local endpoint_path="$1"
  TOKEN="$(databricks postgres generate-database-credential "$endpoint_path" -o json 2>/dev/null \
    | jq -r '.token // empty')"
  EMAIL="$(databricks current-user me -o json 2>/dev/null \
    | jq -r '.userName // .emails[0].value // empty')"
}

# Find the default (main) Lakebase branch
DEFAULT_BRANCH_UID="$(databricks postgres list-branches "$PROJ_PATH" -o json 2>/dev/null \
  | jq -r '(if type == "array" then . elif type == "object" then (.branches // .items // []) else [] end) | .[] | select((.status.default == true) or (.is_default == true)) | (.uid // .id // (if .name then (.name | split("/") | last) else empty end))' | head -1)"

if [ -z "$DEFAULT_BRANCH_UID" ]; then
  echo "connect-main-branch: could not find default Lakebase branch. Check LAKEBASE_PROJECT_ID and 'databricks auth'."
  exit 1
fi

echo "Main Lakebase branch: $DEFAULT_BRANCH_UID"

BRANCH_PATH="${PROJ_PATH}/branches/${DEFAULT_BRANCH_UID}"

# Get existing endpoint host (create if missing, like post-checkout)
HOST="$(databricks postgres list-endpoints "$BRANCH_PATH" -o json 2>/dev/null \
  | jq -r '.[0].status.hosts.host // empty')"

if [ -z "$HOST" ]; then
  echo "connect-main-branch: creating primary endpoint..."
  databricks postgres create-endpoint "$BRANCH_PATH" "primary" \
    --json '{"spec": {"endpoint_type": "ENDPOINT_TYPE_READ_WRITE", "autoscaling_limit_min_cu": 2, "autoscaling_limit_max_cu": 4}}' >/dev/null 2>&1 || true
  echo "Waiting for endpoint to be active..."
  for _ in $(seq 1 24); do
    state="$(databricks postgres list-endpoints "$BRANCH_PATH" -o json 2>/dev/null \
      | jq -r '.[0].status.current_state // empty')"
    [ "$state" = "ACTIVE" ] && break
    sleep 5
  done
  HOST="$(databricks postgres list-endpoints "$BRANCH_PATH" -o json 2>/dev/null \
    | jq -r '.[0].status.hosts.host // empty')"
fi

if [ -z "$HOST" ]; then
  echo "connect-main-branch: could not get endpoint host for main branch."
  exit 1
fi

get_credential "${BRANCH_PATH}/endpoints/primary"
if [ -z "$TOKEN" ] || [ -z "$EMAIL" ]; then
  echo "connect-main-branch: could not generate credential. Check 'databricks auth'."
  exit 1
fi

update_env "$HOST" "$EMAIL" "$TOKEN" "$DEFAULT_BRANCH_UID"
echo "Connected to main branch ($DEFAULT_BRANCH_UID). Updated .env and application-local.properties."
